[build]
  command   = "npx eleventy"
  publish   = "_site"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"   # ensures JSON imports work

[[redirects]]
  from = "/api/jokers"
  to   = "/.netlify/functions/jokers"
  status = 200

[[redirects]]
  from = "/api/stickers"
  to   = "/.netlify/functions/stickers"
  status = 200

[build.environment]
  NODE_VERSION = "20"